{
 "title": "General",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Indicates if mediator service is up and running",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mediator-metrics\"}"
    }
   ]
  },
  {
   "title": "Error count per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5.*|400\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "Avg Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (method, path)(rate(http_request_duration_seconds_count{job=\"mediator-metrics\"}[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Response codes per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code)(rate(http_request_duration_seconds_count{job=\"mediator-metrics\"}[1m]))"
    }
   ]
  }
 ]
}