version: '3'

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
     - cht-net 
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      - mongo_url=mongodb://mongo-db/openhim-development
      - mongo_atnaUrl=mongodb://mongo-db/openhim-development
      - NODE_ENV=development
      - api_authenticationTypes=["token", "basic", "openid", "local"]
      - authentication_enableCustomTokenAuthentication=true
      - authentication_enableJWTAuthentication=true
      - authentication_jwt_secretOrPublicKey=secret
      - authentication_jwt_algorithms=HS256
      - authentication_jwt_issuer=openhim
      - openhimConsoleBaseUrl=http://localhost:9000
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
     - cht-net 
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
     - cht-net 
    ports:
      - "9000:80"
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  mongo-data: